
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: "123456"
  host: localhost

development:
  <<: *default
  database: video_sharing_development

test:
  <<: *default
  database: video_sharing_test

production:
  <<: *default
  database: video_sharing_production
  username: video_sharing
  password: <%= ENV["VIDEO_SHARING_DATABASE_PASSWORD"] %>
